services:
  image: swift-deploy-1-node:latest
  port: 3000
  version: "1.0.0"
  restart_policy: unless-stopped
  mode: canary

nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30
  contact: ops@swiftdeploy.local

opa:
  image: openpolicyagent/opa:latest
  port: 8181

network:
  name: swiftdeploy-net
  driver_type: bridge

volumes:
  logs: app-logs